#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
$HOME/.config/polybar/launch.sh &

# wallpaper
nitrogen --random --set-zoom-fill &

# compositor
picom -b -f &

# reload sxhkdrc
pkill -usr1 -x sxhkd; notify-send 'sxhkd' 'Reloaded config'


bspc monitor -d I II III IV V
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           12
bspc config normal_border_color "#3E3D23"
bspc config focused_border_color "#9E2A2B"
# bspc config focused_border_color "#EBC238"

bscp config focus_follows_pointer  true

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config top_padding          40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

